### ISSUE TITLE
Unable to set blob metadata

### ISSUE THREAD

**Issue by remcohaszing** [GoogleCloudPlatform/google-cloud-python#1185]
I am trying to set custom metadata on a blob. However, this does not work. I'm using the following script:

``` py
#!/usr/bin/env python3
import os

from gcloud import storage

client = storage.Client('super secret id')
bucket = client.get_bucket('super secret bucket')

blob = bucket.blob('kirby.png')
blob.metadata = dict(Color='Pink')
with open(os.path.expanduser('~/Pictures/kirby.png'), 'rb') as img_data:
    blob.upload_from_file(img_data)
```

When retrieving the blob or inspecing it in the developer console, the metadata is still unset.

**Comment by tseaver** [comment]
Setting the `metadata` locally does not cause the instance to make the API call to patch it on the server, and we don't send metadata along with the `upload_from_file()` call.  You need to add a call to `blob.patch()` to persist the changes to `blob.metadata`.

**Comment by remcohaszing** [comment]
I modified the script:
```py
#!/usr/bin/env python3
import os

from gcloud import storage

client = storage.Client('dc-app-api')
bucket = client.get_bucket('appsemble-dev')

blob = bucket.blob('kirby.png')
with open(os.path.expanduser('~/Pictures/kirby.png'), 'rb') as img_data:
    blob.upload_from_file(img_data)
blob.metadata = {'Color': 'Pink', 'Spam': 'Cheese'}
blob.metadata['Foo'] = 'Bar'
blob.patch()
```
This sets the `Color` and `Spam` metadata fields, but not the `Foo` field. There is no warning about this whatsoever.

Also there is no documentation on the `Blob` class on how to update metadata.

**Comment by dhermes** [comment]
Thanks for reporting. Looking into it now.

**Comment by dhermes** [comment]
Ahhh. This is because the `Blob.metadata` [getter returns][1] a `copy.deepcopy` of the dictionary stored, so doing

```python
blob.metadata['Foo'] = 'Bar'
```

updates the copy, not the dictionary actually stored on the `Blob`. We should fix this.

@tseaver WDYT?

[1]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/eb3d390f69055ac09f41c4e395fc35e59800852b/gcloud/storage/blob.py#L665

**Comment by tseaver** [comment]
To allow mutation of the `metadata` in-place (as opposed to assigning to it wholesale), we would need a way to detect those mutations, in order to mark it as changed (for a subsequent call to `blob.patch()` to pick up).

**Comment by dhermes** [comment]
Right. Custom `dict` subclass?

**Comment by tseaver** [comment]
Right, overriding:

- `__delitem__`
- `__setitem__`
- `clear`
- `update`
- `setdefault`
- `pop`
- `popitem`

**Comment by remcohaszing** [comment]
A custom `dict` class could work for the examples I provided. This would still not make a dict behave as expected tough. Since dicts are mutable, I would expect the following to work:

```py
metadata = {'Holy': 'Grail'}
blob.metadata = metadata
metadata['Ministry'] = 'Silly Walks'
blob.patch()
```

If the setter of `blob.metadata` would return this new class, this would no longer refer to the original dict that has been set.

**Comment by remcohaszing** [comment]
I think this subclass could work if no setter is defined. An empty metadata object could be set in the `Blob` constructor. This exposes the metadata as if it is a regular `dict`. This would break with the current behaviour, where setting `metadata` *is* allowed.

**Comment by dhermes** [comment]
The fact that the getter returns a copy is not set in stone. We did it to "protect" the integrity of the actual data own by the class, but didn't think through situations like this.

We don't need a getter, but do need a setter to track changes on the object. Can't have a setter without a getter, so that's just how it's gotta be. (Also, all properties are stored on a non-public attribute called `_properties`, another reason for a getter.)

**Comment by remcohaszing** [comment]
I suppose it could look something like this:
```py
class Metadata(dict):
    def __init__(self, blob):
        self._blob = blob

    def __setitem__(self, key, value):
        super(self, Metadata).__setitem__(key, value)
        self._blob._patch_property('metadata', self)

    # XXX Repeat pattern for other modifier functions


class Blob(_PropertyMixin):
    ...

    def __init__(self, ...)
        ...
        self._properties['metadata'] = Metadata(self)

    @property
    def metadata(self):
        return self._properties['metadata']
```
This marks the metadata as modified if it gets edited and ensures the metadata can't be overridden using a setter.

A side effect is that the metadata property is never `None`. I personally like that better anyway.

**Comment by saxenanurag** [comment]
```python
blob.upload_from_file()
blob.metadata = {'luke': 'skywalker'}
blob.patch()
```
worked for me. I was able to upload a file and apply the meta data after the file upload.

**Comment by tseaver** [comment]
@saxenanurag I'm in the middle of reviewing how we are using the ex-`apitools` code (now in `gcloud.streaming`), and can see how we *should* be able to send the patched metadata along with the upload request.

**Comment by dhermes** [comment]
:+1: What he said :grinning:

**Comment by saxenanurag** [comment]
Thanks.

**Comment by pdknsk** [comment]
I think this is a duplicate of #754. The use of *metadata* is a bit ambiguous as *metadata* refers to both the *metadata* of an object (such as *Cache-Control*) but also the ```metadata``` property, meant for custom *metadata*.

Anyway, to the issue. Any update? The problem with ```patch``` is that the object is online briefly with wrong properties, or less briefly in the freak occurrence of a connection failure between two requests. And, it increases ```metageneration```.

```Python
>>> text = bucket.blob('file.txt')
>>> text.cache_control = 'no-cache'
>>> text.upload_from_string('text')
>>> text.reload()
>>> text.cache_control
>>> text.metageneration
1
>>> text.cache_control = 'no-cache'
>>> text.patch()
>>> text.reload()
>>> text.cache_control
u'no-cache'
>>> text.metageneration
2
```

**Comment by pdknsk** [comment]
I've updated a [previous](https://github.com/GoogleCloudPlatform/google-cloud-python/issues/536#issuecomment-71909652) patch, hack perhaps, which makes it work. It's not tested extensively.

```Diff
--- a/blob.py
+++ b/blob.py
@@ -494,6 +494,11 @@
 
         # Configure the upload request parameters.
         request = Request(upload_url, 'POST', headers)
+
+        if self._properties:
+            headers['content-type'] = 'application/json'
+            request.body = json.dumps(self._properties)
+
         upload.configure_request(upload_config, request, url_builder)
 
         # Configure final URL
```
The file ```google/cloud/storage/blob.py``` is located in your Python ```site-packages``` directory.
```Python
>>> text = bucket.blob('file.txt')
>>> text.cache_control = 'no-cache'
>>> text.metadata = {'custom': 'metadata'}
>>> text.upload_from_string('text')
>>> text.reload()
>>> text.cache_control
u'no-cache'
>>> text.metadata
{u'custom': u'metadata'}
>>> text.metageneration
1
```

**Comment by tseaver** [comment]
#3362 passes along all non-ACL blob properties with the (initial or only) upload request.

**Comment by ajr80231** [comment]
Hey was reading up on this. I was able to set the metadata using patch and dic. But now when I want to pull the metadata it always returns None. Any Reasons why?

**Comment by Prabakaran1410** [comment]
With patch() the metadata of a file is getting updated properly. But this has two operations,
1) First upload a file with no metadata
2) Then updating the metadata using patch()

Is there any option to upload the file along with its metadata? this should be a single step process

**Comment by tseaver** [comment]
@Prabakaran1410 You don't need to call `patch` on the blob after upload:  since PR #3362, all properties assigned to the blob before upload are passed through.

**Comment by paul121** [comment]
I had some trouble getting this to work because the `metadata` was always `None` (even though I manually added values via the Storage UI). Later I realized I was using `bucket.blob("name")` rather than `bucket.get_blog("name")` so the metadata hadn't been loaded. Might help someone else.
