### ISSUE TITLE
Can't pip install google-cloud ?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/google-cloud-python#2298]
(from a customer)

Hi-

I tried installing the newly renamed google-cloud libraries via pip but it doens't look like the python repo got updated.

What this basically means you'd have to use the older gcloud-python version...which is fine but anyone going through our install instructions is in for a surprise (and a pretty miserable experience)

https://github.com/GoogleCloudPlatform/google-cloud-python#quick-start
https://googlecloudplatform.github.io/google-cloud-python/

(env)srashid@srashid-glaptop2:~/Desktop/emulators/pyapp$ pip install google-cloud
Downloading/unpacking google-cloud
  Could not find any downloads that satisfy the requirement google-cloud
Cleaning up...
No distributions at all found for google-cloud
Storing debug log for failure in /home/srashid/.pip/pip.log

in pip.log

Downloading/unpacking google-cloud
  Getting page https://pypi.python.org/simple/google-cloud/
  URLs to search for versions for google-cloud:
  * https://pypi.python.org/simple/google-cloud/
  Analyzing links from page https://pypi.python.org/simple/google-cloud/
  Could not find any downloads that satisfy the requirement google-cloud
Cleaning up...
  Removing temporary dir /home/srashid/Desktop/emulators/pyapp/env/build...
No distributions at all found for google-cloud
Exception information:
Traceback (most recent call last):
  File "/home/srashid/Desktop/emulators/pyapp/env/local/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/home/srashid/Desktop/emulators/pyapp/env/local/lib/python2.7/site-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/home/srashid/Desktop/emulators/pyapp/env/local/lib/python2.7/site-packages/pip/req.py", line 1177, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/home/srashid/Desktop/emulators/pyapp/env/local/lib/python2.7/site-packages/pip/index.py", line 277, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
DistributionNotFound: No distributions at all found for google-cloud

gcloud's references shows:
   https://pypi.python.org/simple/gcloud/

bug google-cloud is empty:
  https://pypi.python.org/simple/google-cloud/

**Comment by daspecster** [comment]
I believe once the 0.19.0 release gets cut, that this will be resolved. 

See: https://github.com/GoogleCloudPlatform/google-cloud-python/pull/2270.

@dhermes, maybe until that release get's cut we should revert the README?

**Comment by dhermes** [comment]
Indeed. Was planning on getting it in on Thursday but there was some pushback. If we don't have movement on it today we can make those temporary edits.

**Comment by Ofekmeister** [comment]
If so, you can re-open/merge this PR @2264 and revert it when the migration is complete.

**Comment by dhermes** [comment]
Thanks for being alert on this @Ofekmeister

**Comment by bjwatson** [comment]
@dhermes I doubt https://github.com/GoogleCloudPlatform/google-cloud-python/issues/2258 will be done today, so it's your choice what release you would like to cut (`0.18.2` or `0.19.0`) to address this immediate concern, knowing that the namespace breaking change will be available in another couple days.

**Comment by dhermes** [comment]
@bjwatson The "immediate concern" can be addressed by just fixing up some docs / README

**Comment by bjwatson** [comment]
Awesome. Thanks @dhermes.

**Comment by dhermes** [comment]
The pressing issue is fixed by #2264 but we still need to cut a final monolithic release and then I'll start work in the release-by-service approach.

**Comment by ryanmcdowell** [comment]
The issue of the install command being wrong was fixed but all of the imports in the examples are still wrong which will cause just as much confusion.

**Comment by jorvis** [comment]
This is helpful to see.  Is this why after installing the modules and following the example for Google Storage I get this?
```
from google.cloud import storage
```
which returns:
```
ImportError: cannot import name storage
```

**Comment by jorvis** [comment]
For those of us just finding this, can someone point out the proper place for an example of accessing Google Storage until the fix is done?  I just installed from the GitHub trunk and the problem persists.

**Comment by dhermes** [comment]
@jorvis Check out http://google-cloud-python.readthedocs.io/en/stable/ and/or https://googlecloudplatform.github.io/google-cloud-python/stable/

The README on https://pypi.python.org/pypi/gcloud is also correct.

**Comment by dhermes** [comment]
Pre-emptively closing since once the [tag builds][1] this will be on PyPI. (The build has been waiting to start for 40+ minutes, so hopefully soon.)

[1]: https://travis-ci.org/GoogleCloudPlatform/google-cloud-python/builds/161121136
