### ISSUE TITLE
Pycodestyle update causing our lint to fail.

### ISSUE THREAD

**Issue by daspecster** [GoogleCloudPlatform/google-cloud-python#2974]
From what I can tell, there are three new errors that pycodestyle is finding.

E306: expected 1 blank line before a nested definition, found 0
~E123: closing bracket does not match indentation of opening bracket's line~
~E722: do not use bare except~

See: #2973

**Comment by dhermes** [comment]
`E123` seems legit

**Comment by daspecster** [comment]
Yeah, I updated the PR to just fix the E123 errors.

**Comment by dhermes** [comment]
I filed https://github.com/PyCQA/pycodestyle/issues/621

**Comment by dhermes** [comment]
They fixed it in `2.3.1`

**Comment by dhermes** [comment]
@daspecster I should've been more specific, they fixed the `E306` false positives. We still have the `E722` and maybe the `E123` issues to deal with

**Comment by daspecster** [comment]
Yeah I saw, maybe closed this too soon, but the rest are resolved in #2973 either way. I have an update to remove the ignore for E306 then it should be good IMO.
