### ISSUE TITLE
Spanner and Storage libs don't play well together

### ISSUE THREAD

**Issue by dr3x** [GoogleCloudPlatform/google-cloud-python#3327]
# Spanner and Storage libs don't play well together

Using the latest version of the code, I can use Spanner and Storage cloud_client separately but get error trying to use them together so there may be some conflict in the dependencies.

If I install the requirements for Spanner first, then Storage, I get this:

```python
>>> from google.cloud import spanner
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\src\github\python-docs-samples\spanner\cloud-client\env\lib\site-packages\google\cloud\spanner\__init__.py", line 18, in <module>
    from google.cloud.spanner.client import Client
  File "C:\src\github\python-docs-samples\spanner\cloud-client\env\lib\site-packages\google\cloud\spanner\client.py", line 42, in <module>
    from google.cloud.spanner.instance import DEFAULT_NODE_COUNT
  File "C:\src\github\python-docs-samples\spanner\cloud-client\env\lib\site-packages\google\cloud\spanner\instance.py", line 33, in <module>
    from google.cloud.spanner.database import Database
  File "C:\src\github\python-docs-samples\spanner\cloud-client\env\lib\site-packages\google\cloud\spanner\database.py", line 35, in <module>
    from google.cloud.spanner.session import Session
  File "C:\src\github\python-docs-samples\spanner\cloud-client\env\lib\site-packages\google\cloud\spanner\session.py", line 28, in <module>
    from google.cloud.spanner.snapshot import Snapshot
  File "C:\src\github\python-docs-samples\spanner\cloud-client\env\lib\site-packages\google\cloud\spanner\snapshot.py", line 22, in <module>
    from google.cloud._helpers import _timedelta_to_duration_pb
ImportError: cannot import name _timedelta_to_duration_pb
```

If Storage first, then Spanner, I get this:

```python
>>> from google.cloud import spanner
>>> from google.cloud import storage
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\src\github\python-docs-samples\spanner\cloud-client\env\lib\site-packages\google\cloud\storage\__init__.py", line 36, in <module>
    from google.cloud.storage.client import Client
  File "C:\src\github\python-docs-samples\spanner\cloud-client\env\lib\site-packages\google\cloud\storage\client.py", line 19, in <module>
    from google.cloud.client import JSONClient
ImportError: cannot import name JSONClient
```

**Comment by dhermes** [comment]
@dr3x This seems like you are installing incompatible versions. Can you run the following for me?

```
$ [sudo] pip install --upgrade pip  # Make sure pip is up to date
$ pip show google-cloud-core google-cloud-spanner google-cloud-storage
```

**Comment by dr3x** [comment]
(env) C:\src\github\python-docs-samples\spanner\cloud-client>pip install --upgrade pip
Requirement already up-to-date: pip in c:\src\github\python-docs-samples\spanner\cloud-client\env\lib\site-packages

(env) C:\src\github\python-docs-samples\spanner\cloud-client>pip show google-cloud-core google-cloud-spanner google-cloud-storage
Name: google-cloud-core
Version: 0.22.1
Summary: API Client library for Google Cloud: Core Helpers
Home-page: https://github.com/GoogleCloudPlatform/google-cloud-python
Author: Google Cloud Platform
Author-email: jjg+google-cloud-python@google.com
License: Apache 2.0
Location: c:\src\github\python-docs-samples\spanner\cloud-client\env\lib\site-packages
Requires: protobuf, httplib2, google-auth, google-auth-httplib2, six, googleapis-common-protos
---
Name: google-cloud-spanner
Version: 0.23.0
Summary: Python Client for Cloud Spanner
Home-page: https://github.com/GoogleCloudPlatform/google-cloud-python
Author: Google Cloud Platform
Author-email: jjg+google-cloud-python@google.com
License: Apache 2.0
Location: c:\src\github\python-docs-samples\spanner\cloud-client\env\lib\site-packages
Requires: google-cloud-core, gapic-google-cloud-spanner-admin-database-v1, gapic-google-cloud-spanner-v1, gapic-google-cloud-spanner-admin-instance-v1, grpcio
---
Name: google-cloud-storage
Version: 0.22.0
Summary: Python Client for Google Cloud Storage
Home-page: https://github.com/GoogleCloudPlatform/google-cloud-python
Author: Google Cloud Platform
Author-email: jjg+google-cloud-python@google.com
License: Apache 2.0
Location: c:\src\github\python-docs-samples\spanner\cloud-client\env\lib\site-packages
Requires: google-cloud-core

(env) C:\src\github\python-docs-samples\spanner\cloud-client>

**Comment by dhermes** [comment]
The latest (and compatible) versions are:

- https://pypi.python.org/pypi/google-cloud-core/0.24.0
- https://pypi.python.org/pypi/google-cloud-spanner/0.24.0
- https://pypi.python.org/pypi/google-cloud-storage/1.0.0

`pip install --upgrade` those three dependencies and your issue should be resolved

I am preemptively closing, but am happy to re-open if this doesn't resolve your issue.

**Comment by dr3x** [comment]
ok verified fixed after running the pip upgrade; however maybe packaging is still an issue because I started by downloading the latest version of the sample code.

pip install --upgrade google-cloud-core
pip install --upgrade google-cloud-spanner
pip install --upgrade google-cloud-storage

Thanks for the quick response :)

**Comment by dhermes** [comment]
> however maybe packaging is still an issue because I started by downloading the latest version of the sample code

Can you clarify what you mean here? Where did you download / which sample code?

**Comment by lukesneeringer** [comment]
Summoning @jonparrott. Sounds like a sample for one of these two probably needs to be updated.

**Comment by jonparrott** [comment]
seems the samples are using the latest versions

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/storage/cloud-client/requirements.txt

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/spanner/cloud-client/requirements.txt

**Comment by dr3x** [comment]
ok disregard, I think it was the rev I had checked out, out of sync dependencies appears to be resolved:

this was the version I was on:
C:\src\github\python-docs-samples [master ≡ +2 ~0 -0 !]> git log
commit c02c187e16238932540ecf62a3185c5bde2a4a25
Author: Gus Class <gguuss@gmail.com>
Date:   Wed Apr 19 14:58:27 2017 -0700

this is the version I am on now:
commit 24e1a79ca95d8a7cd7a6e10553ba0bb333b026ce
Author: Ryan Matsumoto <ryanmats@google.com>
Date:   Tue Apr 25 09:33:05 2017 -0700

Old rev:
C:\src\github\python-docs-samples\spanner\cloud-client\requirements.txt
google-cloud-spanner==0.23.0

C:\src\github\python-docs-samples\storage\cloud-client\requirements.txt
google-cloud-storage==0.22.0
google-cloud-pubsub==0.22.0

New rev:
(env) C:\src\github\python-docs-samples\spanner\cloud-client\equirements.txt
google-cloud-spanner==0.24.0

(env) C:\src\github\python-docs-samples\storage\cloud-client\requirements.txt
google-cloud-storage==1.0.0
google-cloud-pubsub==0.24.0

**Comment by dhermes** [comment]
Sounds good, thanks!
