### ISSUE TITLE
The Python BigQuery client fails on creating a view in standardSQL 

### ISSUE THREAD

**Issue by hm-distro** [GoogleCloudPlatform/google-cloud-python#3388]
```python
from google.cloud import bigquery

bigquery_client = bigquery.Client(project="my-project")
dataset = bigquery_client.dataset("my-dataset")

table = dataset.table("v_test")

#Fails on Standard SQL
#table._properties['view'] = {'query': "select * from `my-project.my.dataset.test_table`",'useLegacySql':False}  

#Works on Legacy SQL
table._properties['view'] = {'query': "select * from [my-project:my-dataset.test_table]",'useLegacySql':True}  

try:
    table.create()
except Exception as err:
    print(err)
```
The https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/bigquery/google/cloud/bigquery/table.py#L355 should also take in another property for useLegacySql

Example  payload at http://stackoverflow.com/questions/33243427/how-can-i-create-a-new-view-in-bigquery-using-the-python-api

**Comment by tseaver** [comment]
The first issue (that the commented out bit fails) seems like a back-end issue:  the [`Table` resource docs](https://cloud.google.com/bigquery/docs/reference/rest/v2/tables#view.useLegacySql) should govern how that flag is used.

WRT how the API surface exposes standard vs. legacy dialects, I'd like to update the `view_query` setter to require standard SQL, and add another one (`view_query_legacy_sql`) to allow creating views with the older dialect.

**Comment by hm-distro** [comment]
Any update?

**Comment by tseaver** [comment]
@hm-distro PR #3514, which I just merged. adds support for a new `view_use_legacy_sql` property.  E.g.,:

```python
from google.cloud import bigquery

bigquery_client = bigquery.Client(project="my-project")
dataset = bigquery_client.dataset("my-dataset")

table = dataset.table("v_test")
table.view_query = "select * from `my-project.my.dataset.test_table`"
table.view_query_legacy_sql = False
table.create()
```

**Comment by hm-distro** [comment]
Thank you.

**Comment by maiskovich** [comment]
@tseaver do you know when this will be available in the Google Cloud client distribution through pip? I am trying with the latest available(google-cloud 0.27.0) and this doesn't work.
Thank you very much

**Comment by tseaver** [comment]
@maiskovich Please update to the latest `google-cloud-bigquery`, e.g.:

```sh
$ /path/to/venv/bin/pip install -U google-cloud-bigquery
```

**Comment by maiskovich** [comment]
@tseaver I tried, but it says: Requirement already up-to-date, tried deleting it and installing again, and still not working

**Comment by maiskovich** [comment]
@tseaver I managed to make it work, the method is table.view_use_legacy_sql = False , in the example it was saying table.view_query_legacy_sql = False
I saw now that at the beginning you put view_use_legacy_sql, but I was just copying the example.

Thank you
