### ISSUE TITLE
Speech: Obscure encoding error message

### ISSUE THREAD

**Issue by chemelnucfin** [GoogleCloudPlatform/google-cloud-python#4928]
Using the wrong encoding for the file results in an error that does not easily point to the right cause.

```
self._exceptiongoogle.api_core.exceptions.GoogleAPICallError:
None Unexpected state: Long-running operation had neither response nor
error set.
```

See 
[#4885](https://github.com/GoogleCloudPlatform/google-cloud-python/issues/4885#issuecomment-366295199) for background info.

**Comment by chemelnucfin** [comment]
@jonparrott Is there anything we can do on our end or would this a backend issue?  Who would I talk to for that?

**Comment by jonparrott** [comment]
@jerjou maybe?

**Comment by HaHatake** [comment]
I also encountered the error "Long-running operation had neither response nor error set"
Is this session timeout ?

**Comment by tseaver** [comment]
`google.api_core.operation.Operation._set_result_from_operation` is raising this error because its `self._operation.done` flag is already true, but neither `error` nor `response` is set.  This is a bug in the backend:  the [API docs for `Operation`](https://cloud.google.com/speech-to-text/docs/reference/rpc/google.longrunning#google.longrunning.Operation) state:

> Union field result. The operation result, which can be either an error or a valid response. If done == false, neither error nor response is set. If done == true, exactly one of error or response is set. result can be only one of the following:
> error | Status                                        The error result of the operation in case of failure or cancellation.
>
> response | Any                                        The normal response of the operation in case of  success. If the original method returns no data on success, such as Delete, the response is google.protobuf.Empty. If the original method is standard Get/Create/Update, the response should be the resource. For other methods, the response should have the type XxxResponse, where Xxx is the original method name. For example, if the original method name is TakeSnapshot(), the inferred response type is TakeSnapshotResponse.

@theacodes, @crwilcox please loop in the appropriate PoC for the Speech API team.

**Comment by tseaver** [comment]
@theacodes, @crwilcox Who is our back-end PoC for the Speech API?

**Comment by jerjou** [comment]
I thought I fixed this. Is this still happening?

**Comment by jerjou** [comment]
Assigning to me might not be the best idea... I'm leaving in a week or two..

**Comment by tseaver** [comment]
@jerjou Was your fix in the back-end?  I saw your first pass at it in PR #5406, but you closed it without a merge, noting:

> Just to close the loop on this - turns out it was a server error.

**Comment by jerjou** [comment]
Oh - yes. It was.

**Comment by tseaver** [comment]
@jerjou Can we close this issue because that fix is deployed in production?

**Comment by jerjou** [comment]
Yup!

**Comment by tseaver** [comment]
W00t!  Thanks, @jerjou .

**Comment by flavienbwk** [comment]
Issue is still active for the Google Cloud Speech API in Python (diarization).

**Comment by JOSEPHNAVIN** [comment]
Any update on this issue ?

**Comment by Napoleon-Black** [comment]
I faced the same problem. I'm using Python 3.7 and the latest versions of google-cloud-speech and
google-cloud-storage.

**Comment by JeffersonH44** [comment]
I'm also experiencing the same problem with python 3.6 and 3.7, with the gcloud command it works

**Comment by NikolayPogoreliy** [comment]
Yea!!! I have the same trouble with google-cloud-speech and
google-cloud-storage on Python3.6. 
PS 
@tseaver It's seems like no one care(((

**Comment by JeffersonH44** [comment]
for those who doesn't know, there's an issue in the issue tracker here:

https://issuetracker.google.com/issues/122732566

it seems that the problem is when speech doesn't detect anything on the audio that doesn't retrieve any "friendly" message
